### ISSUE TITLE
New react-konva

### ISSUE THREAD

**Issue by lavrton** [olimsaidov/react-konva#4]
Hello. Konva maintainer is there.

I made new version of `react-konva` https://github.com/lavrton/react-konva.
It is based on https://github.com/reactjs/react-art and should work much better then current implementation as it does not create DOM nodes for each `Konva.Node`.

I want to use `react-konva` name to publish new version to npm. @olimsaidov do you still interested in current or in new version? Can you transfer ownership of the package?

**Comment by olimsaidov** [comment]
Hi, @lavrton.

Sorry for the late response. I've added you as package owner. 
I'll mark this repo as discontinued. 

Nice job.
